# Generated by Django 5.2.17 on 2026-09-27 13:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


def copy_existing_rm_data(apps, schema_editor):
    Employee = apps.get_model("employee", "Employee")
    StudentProfile = apps.get_model("employee", "StudentProfile")
    valid_goals = {"Defence", "UPSC / Civil Services", "NEET UG", "NEET PG", "Other"}
    legacy_goals = {
        "Defence Services": "Defence",
        "Competitive Examination": "UPSC / Civil Services",
        "Higher Education": "Other",
        "Employment": "Other",
        "Entrepreneurship": "Other",
        "Skill Development": "Other",
        "Sports": "Other",
        "Arts": "Other",
    }
    for employee in Employee.objects.iterator():
        info = (employee.additional_info or {}).get("youth_centre", {})
        if not info:
            continue
        goal = info.get("student_goal") or info.get("student_aim_category") or ""
        goal = legacy_goals.get(goal, goal)
        if goal not in valid_goals:
            goal = "Other" if goal else ""
        registration_date = info.get("student_joining_date") or None
        StudentProfile.objects.get_or_create(
            employee_id=employee.id,
            defaults={
                "career_goal": goal,
                "defence_entry": (info.get("student_defence_entry_scheme") or "").replace("Other Indian Army Entry Scheme", "Other Entry Scheme"),
                "institution": info.get("student_institution") or "",
                "guardian_name": info.get("student_guardian_name") or "",
                "guardian_phone": info.get("student_guardian_contact") or "",
                "notes": info.get("student_initial_notes") or "",
                "registration_date": registration_date or datetime.date.today(),
            },
        )


def reverse_copy(apps, schema_editor):
    # Original JSON is deliberately retained, so reverse needs no data action.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_remove_policy_specific_employees_policy_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_of_rm', models.CharField(blank=True, choices=[('Self Study', 'Self Study'), ('Competitive Exam Preparation', 'Competitive Exam Preparation'), ('Career Guidance', 'Career Guidance'), ('Access to Study Material', 'Access to Study Material'), ('Internet / Digital Resources', 'Internet / Digital Resources'), ('Counselling / Mentorship', 'Counselling / Mentorship'), ('Skill Development', 'Skill Development'), ('Other', 'Other')], max_length=80)),
                ('purpose_other', models.CharField(blank=True, max_length=200)),
                ('career_goal', models.CharField(blank=True, choices=[('Defence', 'Defence'), ('UPSC / Civil Services', 'UPSC / Civil Services'), ('NEET UG', 'NEET UG'), ('NEET PG', 'NEET PG'), ('Other', 'Other')], max_length=40)),
                ('defence_entry', models.CharField(blank=True, choices=[('NDA', 'NDA'), ('TES', 'TES'), ('Other Entry Scheme', 'Other Entry Scheme')], max_length=40)),
                ('expectations', models.TextField(blank=True)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('requirements_other', models.CharField(blank=True, max_length=200)),
                ('registration_date', models.DateField(default=datetime.date.today)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('guardian_name', models.CharField(blank=True, max_length=200)),
                ('guardian_phone', models.CharField(blank=True, max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('current_status', models.CharField(blank=True, choices=[('Studying at School / College', 'Studying at School / College'), ('Preparing from Home', 'Preparing from Home'), ('Preparing at Another Institute', 'Preparing at Another Institute'), ('Employed', 'Employed'), ('Joined Armed Forces / Selected', 'Joined Armed Forces / Selected'), ('Joined Professional Course', 'Joined Professional Course'), ('Moved / Relocated', 'Moved / Relocated'), ('No Longer Interested', 'No Longer Interested'), ('Unable to Contact', 'Unable to Contact'), ('Other', 'Other')], max_length=80)),
                ('inactivity_reason', models.TextField(blank=True)),
                ('last_followup_date', models.DateField(blank=True, null=True)),
                ('followup_notes', models.TextField(blank=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rm_profile', to='employee.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['career_goal'], name='rm_profile_goal_idx'), models.Index(fields=['registration_date'], name='rm_profile_reg_idx')],
            },
        ),
        migrations.RunPython(copy_existing_rm_data, reverse_copy),
    ]
