# Generated by Django 5.2.17 on 2026-09-29 05:54

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_add_rm_student_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('called_on', models.DateField(default=datetime.date.today)),
                ('result', models.CharField(choices=[('Studying at School / College', 'Studying at school / college'), ('Preparing from Home', 'Preparing from home'), ('Preparing at Another Institute', 'Preparing at another institute'), ('Plans to Return', 'Plans to come back'), ('Employed', 'Employed'), ('Joined Armed Forces / Selected', 'Selected (armed forces / service)'), ('Joined Professional Course', 'Joined a professional course'), ('Moved / Relocated', 'Moved away'), ('No Longer Interested', 'No longer interested'), ('Unable to Contact', "Couldn't reach them"), ('Wrong Number', 'Wrong number'), ('Other', 'Other')], max_length=80)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('next_call_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-called_on', '-created_at'),
            },
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='goal_detail',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='locality',
            field=models.CharField(blank=True, choices=[('Kupwara', 'Kupwara'), ('Handwara', 'Handwara'), ('Trehgam', 'Trehgam'), ('Kralpora', 'Kralpora'), ('Lolab', 'Lolab'), ('Sogam', 'Sogam'), ('Villgam', 'Villgam'), ('Drugmulla', 'Drugmulla'), ('Kalaroos', 'Kalaroos'), ('Karnah', 'Karnah'), ('Machil', 'Machil'), ('Langate', 'Langate'), ('Qalamabad', 'Qalamabad'), ('Rajwar', 'Rajwar'), ('Zachaldara', 'Zachaldara'), ('Magam', 'Magam'), ('Chowkibal', 'Chowkibal'), ('Keran', 'Keran'), ('Other', 'Other')], max_length=40),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='next_call_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='outcome',
            field=models.CharField(blank=True, choices=[('Selected', 'Selected'), ('Joined Professional Course', 'Joined a professional course'), ('Moved Away', 'Moved away'), ('Closed', 'No longer interested')], max_length=40),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='outcome_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='prep_stage',
            field=models.CharField(blank=True, choices=[('Just starting', 'Just starting'), ('Building basics', 'Building basics'), ('Regular practice & mock tests', 'Regular practice & mock tests'), ('Appeared before', 'Appeared before, trying again'), ('Awaiting result', 'Awaiting result')], max_length=40),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='target_exam',
            field=models.CharField(blank=True, choices=[('UPSC Civil Services', 'UPSC Civil Services'), ('JKPSC (JKAS)', 'JKPSC (JKAS)'), ('JKSSB', 'JKSSB'), ('JK Police', 'JK Police'), ('SSC', 'SSC'), ('JEE', 'JEE (engineering)'), ('Banking', 'Banking'), ('Teaching', 'Teaching'), ('Nursing / Paramedical', 'Nursing / paramedical'), ('Skill / Vocational', 'Skill / vocational'), ('Other', 'Other')], max_length=40),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='target_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='current_status',
            field=models.CharField(blank=True, choices=[('Studying at School / College', 'Studying at school / college'), ('Preparing from Home', 'Preparing from home'), ('Preparing at Another Institute', 'Preparing at another institute'), ('Plans to Return', 'Plans to come back'), ('Employed', 'Employed'), ('Joined Armed Forces / Selected', 'Selected (armed forces / service)'), ('Joined Professional Course', 'Joined a professional course'), ('Moved / Relocated', 'Moved away'), ('No Longer Interested', 'No longer interested'), ('Unable to Contact', "Couldn't reach them"), ('Wrong Number', 'Wrong number'), ('Other', 'Other')], max_length=80),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='defence_entry',
            field=models.CharField(blank=True, choices=[('NDA', 'NDA'), ('TES', 'TES'), ('CDS', 'CDS'), ('AFCAT', 'AFCAT'), ('Agniveer', 'Agniveer'), ('Territorial Army / JKLI', 'Territorial Army / JKLI'), ('Other Entry Scheme', 'Other entry scheme')], max_length=40),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='purpose_of_rm',
            field=models.CharField(blank=True, choices=[('Competitive Exam Preparation', 'Competitive exam preparation'), ('Self Study', 'Self study'), ('Career Guidance', 'Career guidance'), ('Skill Development', 'Skill development'), ('Other', 'Other')], max_length=80),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['outcome'], name='rm_profile_outcome_idx'),
        ),
        migrations.AddField(
            model_name='studentfollowup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentfollowup',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='employee.studentprofile'),
        ),
        migrations.AddIndex(
            model_name='studentfollowup',
            index=models.Index(fields=['called_on'], name='rm_followup_date_idx'),
        ),
    ]
